<a href="https://colab.research.google.com/github/gaby1719/activity/blob/main/Agrupacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/gaby1719/activity/refs/heads/main/archivos/clave_D_agrupacion.csv"
df = pd.read_csv(url)
df.head()

,registro_id,edad,ingresos,frecuencia_uso,gasto_promedio,satisfaccion,reclamos,antiguedad_meses
0,D-R0063,35,444,1.58,5.00,8.00,1,17
1,D-R0103,49,712,8.23,74.67,8.89,2,22
2,D-R0141,49,1632,9.47,150.66,7.90,0,36
3,D-R0077,39,968,8.16,91.96,9.59,12,12
4,D-R0119,34,675,5.66,59.92,9.03,0,16

In [3]:
df.shape

(242, 8)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   registro_id       242 non-null    object
 1   edad              242 non-null    int64
 2   ingresos          242 non-null    int64
 3   frecuencia_uso    242 non-null    float64
 4   gasto_promedio    242 non-null    float64
 5   satisfaccion      241 non-null    float64
 6   reclamos          242 non-null    int64
 7   antiguedad_meses  242 non-null    int64
dtypes: float64(3), int64(4), object(1)
memory usage: 15.3+ KB

In [5]:
df.isnull().sum()

registro_id         0
edad                0
ingresos            0
frecuencia_uso      0
gasto_promedio      0
satisfaccion        1
reclamos            0
antiguedad_meses    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.describe()

,edad,ingresos,frecuencia_uso,gasto_promedio,satisfaccion,reclamos,antiguedad_meses
count,242.000000,242.000000,242.000000,242.000000,241.000000,242.000000,242.000000
mean,36.772727,997.128099,5.319050,78.499298,6.970415,2.384298,18.210744
std,9.830619,426.250871,3.027457,47.271889,1.804123,2.007517,13.054029
min,18.000000,300.000000,0.000000,5.000000,3.200000,0.000000,1.000000
25%,29.000000,655.500000,2.722500,45.110000,5.440000,1.000000,8.000000
50%,37.000000,935.000000,5.365000,72.465000,7.190000,2.000000,16.000000
75%,44.000000,1285.000000,7.872500,105.945000,8.430000,4.000000,26.000000
max,62.000000,2900.000000,14.580000,260.000000,10.000000,12.000000,52.000000

In [9]:
print(df.columns)

Index(['registro_id', 'edad', 'ingresos', 'frecuencia_uso', 'gasto_promedio',
       'satisfaccion', 'reclamos', 'antiguedad_meses'],
      dtype='object')

In [10]:
df["gasto_promedio"].value_counts()

gasto_promedio
5.00      10
138.78     2
150.66     1
74.67      1
59.92      1
          ..
144.77     1
89.39      1
41.32      1
71.58      1
129.93     1
Name: count, Length: 232, dtype: int64

In [11]:
variables_numericas = ["ingresos", "edad"]

for columna in variables_numericas:
    media = df[columna].mean()
    desviacion = df[columna].std()

    limite_inferior = media - 2 * desviacion
    limite_superior = media + 2 * desviacion

    atipicos = df[
        (df[columna] < limite_inferior) |
        (df[columna] > limite_superior)
    ]

    print("Variable:", columna)
    print("Media:", round(media, 2))
    print("Desviación estándar:", round(desviacion, 2))
    print("Límite inferior:", round(limite_inferior, 2))
    print("Límite superior:", round(limite_superior, 2))
    print("Cantidad de valores atípicos:", len(atipicos))

Variable: ingresos
Media: 997.13
Desviación estándar: 426.25
Límite inferior: 144.63
Límite superior: 1849.63
Cantidad de valores atípicos: 4
Variable: edad
Media: 36.77
Desviación estándar: 9.83
Límite inferior: 17.11
Límite superior: 56.43
Cantidad de valores atípicos: 4