<a href="https://colab.research.google.com/github/gaby1719/activity/blob/main/asociacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from itertools import combinations

In [2]:
url = "https://raw.githubusercontent.com/gaby1719/activity/refs/heads/main/archivos/clave_D_asociacion.csv"
df = pd.read_csv(url)
df.head()

,transaccion_id,cliente_id,fecha,categoria,item,cantidad,canal
0,D-T0001,D-C0015,2026-04-02,Bebidas,Chocolate,1,Telefono
1,D-T0001,D-C0015,2026-04-02,Extras,Leche_extra,1,Telefono
2,D-T0001,D-C0015,2026-04-02,Salados,Wrap,1,Telefono
3,D-T0002,D-C0079,2026-01-21,Bebidas,Cafe_americano,1,Web
4,D-T0002,D-C0079,2026-01-21,Salados,Ensalada,1,Web

In [3]:
df.shape

(607, 7)

In [4]:
df.columns

Index(['transaccion_id', 'cliente_id', 'fecha', 'categoria', 'item',
       'cantidad', 'canal'],
      dtype='object')

In [5]:
df.head()

,transaccion_id,cliente_id,fecha,categoria,item,cantidad,canal
0,D-T0001,D-C0015,2026-04-02,Bebidas,Chocolate,1,Telefono
1,D-T0001,D-C0015,2026-04-02,Extras,Leche_extra,1,Telefono
2,D-T0001,D-C0015,2026-04-02,Salados,Wrap,1,Telefono
3,D-T0002,D-C0079,2026-01-21,Bebidas,Cafe_americano,1,Web
4,D-T0002,D-C0079,2026-01-21,Salados,Ensalada,1,Web

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaccion_id  607 non-null    object
 1   cliente_id      607 non-null    object
 2   fecha           607 non-null    object
 3   categoria       607 non-null    object
 4   item            607 non-null    object
 5   cantidad        607 non-null    int64
 6   canal           606 non-null    object
dtypes: int64(1), object(6)
memory usage: 33.3+ KB

In [7]:
df.isnull().sum()

transaccion_id    0
cliente_id        0
fecha             0
categoria         0
item              0
cantidad          0
canal             1
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df.describe()

         cantidad
count  607.000000
mean     1.459638
std      0.752072
min      1.000000
25%      1.000000
50%      1.000000
75%      2.000000
max      4.000000

In [11]:
df["cantidad"].describe()

count    607.000000
mean       1.459638
std        0.752072
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        4.000000
Name: cantidad, dtype: float64

In [13]:
df["categoria"].describe()

count         607
unique          5
top       Bebidas
freq          158
Name: categoria, dtype: object

In [15]:
limite_inferior = 0
limite_superior = 0
variables_numericas = ["cantidad"]

for columna in variables_numericas:
    media = df[columna].mean()
    desviacion_estandar = df[columna].std()

    limite_inferior = media - 2 * desviacion_estandar
    limite_superior = media + 2 * desviacion_estandar

    outliers = df[
        (df[columna] < limite_inferior) |
        (df[columna] > limite_superior)
    ]

    print("Variable:", columna)
    print("Media:", round(media, 2))
    print("Desviación estándar:", round(desviacion_estandar, 2))
    print("Límite inferior:", round(limite_inferior, 2))
    print("Límite superior:", round(limite_superior, 2))
    print("Cantidad de valores atípicos:", len(outliers))
    print("-" * 40)

Variable: cantidad
Media: 1.46
Desviación estándar: 0.75
Límite inferior: -0.04
Límite superior: 2.96
Cantidad de valores atípicos: 64
----------------------------------------

In [17]:
df["categoria"].value_counts()

categoria
Bebidas       158
Reposteria    151
Salados       110
Combos        110
Extras         78
Name: count, dtype: int64

In [19]:
df["canal"].value_counts()

canal
Tienda      271
Web         167
App         138
Telefono     30
Name: count, dtype: int64

In [21]:
df["item"].value_counts()

item
Galleta             49
Cafe_americano      48
Latte               48
Muffin              43
Croissant           42
Sandwich            41
Combo_estudiante    41
Capuchino           40
Hielo               31
Combo_oficina       24
Ensalada            24
Combo_desayuno      24
Panini              23
Chocolate           22
Wrap                22
Combo_tarde         21
Sirope              18
Leche_extra         17
Dona                17
Crema_batida        12
Name: count, dtype: int64

In [22]:
columnas_asociacion = [
    "transaccion_id",
    "cliente_id",
    "fecha",
    "categoria",
    "item",
    "cantidad",
    "canal"
]

In [23]:
df_asociacion = df[columnas_asociacion].copy()

df_asociacion.head()

,transaccion_id,cliente_id,fecha,categoria,item,cantidad,canal
0,D-T0001,D-C0015,2026-04-02,Bebidas,Chocolate,1,Telefono
1,D-T0001,D-C0015,2026-04-02,Extras,Leche_extra,1,Telefono
2,D-T0001,D-C0015,2026-04-02,Salados,Wrap,1,Telefono
3,D-T0002,D-C0079,2026-01-21,Bebidas,Cafe_americano,1,Web
4,D-T0002,D-C0079,2026-01-21,Salados,Ensalada,1,Web

In [24]:
for columna in columnas_asociacion:
    print(columna, df_asociacion[columna].unique())

transaccion_id ['D-T0001' 'D-T0002' 'D-T0003' 'D-T0004' 'D-T0005' 'D-T0006' 'D-T0007'
 'D-T0008' 'D-T0009' 'D-T0010' 'D-T0011' 'D-T0012' 'D-T0013' 'D-T0014'
 'D-T0015' 'D-T0016' 'D-T0017' 'D-T0018' 'D-T0019' 'D-T0020' 'D-T0021'
 'D-T0022' 'D-T0023' 'D-T0024' 'D-T0025' 'D-T0026' 'D-T0027' 'D-T0028'
 'D-T0029' 'D-T0030' 'D-T0031' 'D-T0032' 'D-T0033' 'D-T0034' 'D-T0035'
 'D-T0036' 'D-T0037' 'D-T0038' 'D-T0039' 'D-T0040' 'D-T0041' 'D-T0042'
 'D-T0043' 'D-T0044' 'D-T0045' 'D-T0046' 'D-T0047' 'D-T0048' 'D-T0049'
 'D-T0050' 'D-T0051' 'D-T0052' 'D-T0053' 'D-T0054' 'D-T0055' 'D-T0056'
 'D-T0057' 'D-T0058' 'D-T0059' 'D-T0060' 'D-T0061' 'D-T0062' 'D-T0063'
 'D-T0064' 'D-T0065' 'D-T0066' 'D-T0067' 'D-T0068' 'D-T0069' 'D-T0070'
 'D-T0071' 'D-T0072' 'D-T0073' 'D-T0074' 'D-T0075' 'D-T0076' 'D-T0077'
 'D-T0078' 'D-T0079' 'D-T0080' 'D-T0081' 'D-T0082' 'D-T0083' 'D-T0084'
 'D-T0085' 'D-T0086' 'D-T0087' 'D-T0088' 'D-T0089' 'D-T0090' 'D-T0091'
 'D-T0092' 'D-T0093' 'D-T0094' 'D-T0095' 'D-T0096' 'D-T0097' 'D-T0098'
 'D-T0099' 'D-T0100' 'D-T0101' 'D-T0102' 'D-T0103' 'D-T0104' 'D-T0105'
 'D-T0106' 'D-T0107' 'D-T0108' 'D-T0109' 'D-T0110' 'D-T0111' 'D-T0112'
 'D-T0113' 'D-T0114' 'D-T0115' 'D-T0116' 'D-T0117' 'D-T0118' 'D-T0119'
 'D-T0120' 'D-T0121' 'D-T0122' 'D-T0123' 'D-T0124' 'D-T0125' 'D-T0126'
 'D-T0127' 'D-T0128' 'D-T0129' 'D-T0130' 'D-T0131' 'D-T0132' 'D-T0133'
 'D-T0134' 'D-T0135' 'D-T0136' 'D-T0137' 'D-T0138' 'D-T0139' 'D-T0140'
 'D-T0141' 'D-T0142' 'D-T0143' 'D-T0144' 'D-T0145' 'D-T0146' 'D-T0147'
 'D-T0148' 'D-T0149' 'D-T0150' 'D-T0151' 'D-T0152' 'D-T0153' 'D-T0154'
 'D-T0155' 'D-T0156' 'D-T0157' 'D-T0158' 'D-T0159' 'D-T0160' 'D-T0161'
 'D-T0162' 'D-T0163' 'D-T0164' 'D-T0165' 'D-T0166' 'D-T0167' 'D-T0168'
 'D-T0169' 'D-T0170' 'D-T0171' 'D-T0172' 'D-T0173' 'D-T0174' 'D-T0175'
 'D-T0176' 'D-T0177' 'D-T0178' 'D-T0179' 'D-T0180']
cliente_id ['D-C0015' 'D-C0079' 'D-C0010' 'D-C0027' 'D-C0006' 'D-C0029' 'D-C0004'
 'D-C0070' 'D-C0036' 'D-C0032' 'D-C0066' 'D-C0018' 'D-C0059' 'D-C0001'
 'D-C0074' 'D-C0071' 'D-C0026' 'D-C0065' 'D-C0068' 'D-C0069' 'D-C0037'
 'D-C0011' 'D-C0064' 'D-C0045' 'D-C0022' 'D-C0055' 'D-C0046' 'D-C0003'
 'D-C0013' 'D-C0024' 'D-C0039' 'D-C0093' 'D-C0095' 'D-C0083' 'D-C0028'
 'D-C0049' 'D-C0042' 'D-C0038' 'D-C0053' 'D-C0012' 'D-C0043' 'D-C0050'
 'D-C0008' 'D-C0031' 'D-C0077' 'D-C0023' 'D-C0067' 'D-C0054' 'D-C0025'
 'D-C0002' 'D-C0005' 'D-C0033' 'D-C0092' 'D-C0058' 'D-C0048' 'D-C0060'
 'D-C0007' 'D-C0035' 'D-C0051' 'D-C0052' 'D-C0085' 'D-C0009' 'D-C0047'
 'D-C0073' 'D-C0057' 'D-C0084' 'D-C0017' 'D-C0081' 'D-C0019' 'D-C0041'
 'D-C0044' 'D-C0091' 'D-C0020' 'D-C0040' 'D-C0090' 'D-C0030' 'D-C0088'
 'D-C0063' 'D-C0016' 'D-C0076' 'D-C0014' 'D-C0089']
fecha ['2026-04-02' '2026-01-21' '2026-03-06' '2026-03-23' '2026-01-04'
 '2026-04-27' '2026-03-30' '2026-01-15' '2026-02-26' '2026-03-07'
 '2026-02-27' '2026-02-11' '2026-03-15' '2026-01-16' '2026-02-21'
 '2026-04-12' '2026-04-11' '2026-04-19' '2026-01-18' '2026-04-30'
 '2026-03-17' '2026-02-02' '2026-01-29' '2026-01-02' '2026-03-27'
 '2026-04-03' '2026-04-24' '2026-02-19' '2026-01-06' '2026-03-29'
 '2026-03-12' '2026-03-11' '2026-04-15' '2026-02-17' '2026-01-03'
 '2026-02-28' '2026-01-05' '2026-04-05' '2026-02-12' '2026-04-01'
 '2026-04-06' '2026-04-04' '2026-01-07' '2026-04-13' '2026-03-31'
 '2026-03-21' '2026-03-18' '2026-03-26' '2026-03-09' '2026-03-05'
 '2026-01-23' '2026-03-16' '2026-02-07' '2026-01-26' '2026-01-22'
 '2026-02-03' '2026-04-29' '2026-02-13' '2026-03-19' '2026-02-09'
 '2026-03-01' '2026-04-08' '2026-04-18' '2026-04-09' '2026-01-30'
 '2026-04-23' '2026-02-20' '2026-03-02' '2026-04-07' '2026-04-16'
 '2026-04-22' '2026-02-23' '2026-02-01' '2026-01-01' '2026-02-22'
 '2026-05-01' '2026-04-10' '2026-03-28' '2026-03-22' '2026-04-25'
 '2026-01-17' '2026-02-18' '2026-01-08' '2026-02-16' '2026-04-21'
 '2026-02-25' '2026-03-13' '2026-03-04' '2026-01-28' '2026-03-20'
 '2026-01-09' '2026-01-20' '2026-01-25' '2026-02-14' '2026-04-14'
 '2026-01-11' '2026-01-24' '2026-02-24']
categoria ['Bebidas' 'Extras' 'Salados' 'Reposteria' 'Combos']
item ['Chocolate' 'Leche_extra' 'Wrap' 'Cafe_americano' 'Ensalada' 'Latte'
 'Capuchino' 'Croissant' 'Combo_tarde' 'Sirope' 'Muffin' 'Hielo'
 'Sandwich' 'Panini' 'Galleta' 'Combo_estudiante' 'Combo_desayuno' 'Dona'
 'Combo_oficina' 'Crema_batida']
cantidad [1 2 4 3]
canal ['Telefono' 'Web' 'App' 'Tienda' nan]

In [25]:
df_asociacion_bool = df_asociacion.astype(bool)

df_asociacion_bool.head()

   transaccion_id  cliente_id  fecha  categoria  item  cantidad  canal
0            True        True   True       True  True      True   True
1            True        True   True       True  True      True   True
2            True        True   True       True  True      True   True
3            True        True   True       True  True      True   True
4            True        True   True       True  True      True   True

In [26]:
df_asociacion_bool.dtypes

transaccion_id    bool
cliente_id        bool
fecha             bool
categoria         bool
item              bool
cantidad          bool
canal             bool
dtype: object

In [28]:
df_asociacion_encoded = pd.crosstab(df_asociacion['transaccion_id'], df_asociacion['item'])
frecuencias = df_asociacion_encoded.sum().sort_values(ascending=False)
frecuencias

item
Galleta             49
Cafe_americano      48
Latte               48
Muffin              43
Croissant           42
Combo_estudiante    41
Sandwich            41
Capuchino           40
Hielo               31
Combo_desayuno      24
Ensalada            24
Combo_oficina       24
Panini              23
Chocolate           22
Wrap                22
Combo_tarde         21
Sirope              18
Dona                17
Leche_extra         17
Crema_batida        12
dtype: int64

In [30]:
total_transacciones = df_asociacion_encoded.shape[0]
porcentajes = (frecuencias / total_transacciones * 100).sort_values(ascending=False)

porcentajes.round(2)

item
Galleta             27.22
Cafe_americano      26.67
Latte               26.67
Muffin              23.89
Croissant           23.33
Combo_estudiante    22.78
Sandwich            22.78
Capuchino           22.22
Hielo               17.22
Combo_desayuno      13.33
Ensalada            13.33
Combo_oficina       13.33
Panini              12.78
Chocolate           12.22
Wrap                12.22
Combo_tarde         11.67
Sirope              10.00
Dona                 9.44
Leche_extra          9.44
Crema_batida         6.67
dtype: float64

In [31]:
for grupo_a, grupo_b in combinations(columnas_asociacion, 2):
    soporte = (df_asociacion_bool[grupo_a] & df_asociacion_bool[grupo_b]).mean()

    if soporte > 0.10:
        print(grupo_a, "+", grupo_b, "=", round(soporte, 4))

transaccion_id + cliente_id = 1.0
transaccion_id + fecha = 1.0
transaccion_id + categoria = 1.0
transaccion_id + item = 1.0
transaccion_id + cantidad = 1.0
transaccion_id + canal = 1.0
cliente_id + fecha = 1.0
cliente_id + categoria = 1.0
cliente_id + item = 1.0
cliente_id + cantidad = 1.0
cliente_id + canal = 1.0
fecha + categoria = 1.0
fecha + item = 1.0
fecha + cantidad = 1.0
fecha + canal = 1.0
categoria + item = 1.0
categoria + cantidad = 1.0
categoria + canal = 1.0
item + cantidad = 1.0
item + canal = 1.0
cantidad + canal = 1.0

In [32]:
df_asociacion_bool.to_csv("Ejercicio_asociacion.csv", index=False)

print("\nDataset preparado correctamente para reglas de asociación.")

Dataset preparado correctamente para reglas de asociación.